import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useCallback, useState } from 'react';
import styles from '../styles/Home.module.css'

import Rollbar from 'rollbar';
import { useRollbar, RollbarContext } from '@rollbar/react';

const Home: NextPage = () => {
  const rollbarConfig = {
    autoInstrument: {
      network: true,
      networkResponseHeaders: true,
      networkResponseBody: true,
      networkRequestBody: true,
      log: true,
      dom: false,
      navigation: true,
      connectivity: true
    }
  }
  const rollbar = new Rollbar(rollbarConfig);

  const sendMessage = useCallback(async () => {
    await fetch("/api/hello", { headers: new Headers({"content-type": "application/json"}) })
    rollbar.info('manual message');
  }, [rollbar])

  const [errorState, setErrorState] = useState(false);

  if (errorState) {
    throw new Error('uncaught error (nextjs)');
  }

  return (
    <RollbarContext instance={rollbar}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
  
          <p className={styles.description}>
            Get started by sending a message{' '}
            <button onClick={sendMessage}>send</button>{' '}
            or throwing an uncaught exception{' '}
            <button onClick={() => setErrorState(true)}>throw</button>
          </p>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </RollbarContext>
  )
}

export default Home
